# usage
#
# . base.sh
#
# tmux_wrapper_host=192.168.1.1
# tmux_wrapper_color=cyan
#
# tmux_wrapper_build_bind(){
#	  # bind key, window name, path
#	  tmux_wrapper_bind c name /path/to/dir
# }
#
# tmux_wrapper_main


# suppported options and defaults
#
# tmux_wrapper_host    : ssh remote host           ; localhost
# tmux_wrapper_color   : status line color         ; green
#
# tmux_wrapper_build_bind() : build bind key config
#
# tmux_wrapper_file                : specify base .tmux.conf   ; ~/.tmux.conf
# tmux_wrapper_term                : screen or screen-256color ; screen-256color
# tmux_wrapper_initial_window_name : initial window name
# tmux_wrapper_initial_window_path : initial window path
#
# tmux_wrapper_id        : using socket, or config path    ; tmux${0//\/-}
# tmux_wrapper_session   : name of tmux session            ; <$(basename $0)>
# tmux_wrapper_work_path : working directory use in script ; ~/.tmux.wrapper

tmux_wrapper_main(){
	if [ -z "$tmux_wrapper_file" ]; then
		tmux_wrapper_file=~/.tmux.conf
	fi
	if [ -z "$tmux_wrapper_work_path" ]; then
		tmux_wrapper_work_path=~/.tmux.wrapper
	fi
	if [ -z "$tmux_wrapper_term" ]; then
		tmux_wrapper_term=screen-256color
	fi
	if [ -z "$tmux_wrapper_host" ]; then
		tmux_wrapper_host=localhost
	fi
	if [ -z "$tmux_wrapper_color" ]; then
		tmux_wrapper_color=green
	fi

	if [ -z "$tmux_wrapper_id" ]; then
		tmux_wrapper_id="tmux${0//\//-}"
	fi
	if [ -z "$tmux_wrapper_session" ]; then
		tmux_wrapper_session="<$(basename $0)>"
	fi

	tmux_wrapper_work=$tmux_wrapper_work_path/$tmux_wrapper_id.conf
	tmux_wrapper_socket=$tmux_wrapper_work_path/$tmux_wrapper_id.sock

	cp "$tmux_wrapper_file" "$tmux_wrapper_work"
	echo >> "$tmux_wrapper_work"
	echo "# generated by tmux-wrapper" >> "$tmux_wrapper_work"
	echo >> "$tmux_wrapper_work"
	echo 'set -g default-terminal "'$tmux_wrapper_term'"' >> "$tmux_wrapper_work"
	echo 'set -g status-left "#[fg='$tmux_wrapper_color']'$tmux_wrapper_session'"' >> "$tmux_wrapper_work"
	echo 'set -g status-right "#[fg='$tmux_wrapper_color'][#(ssh '$tmux_wrapper_host' uptime | sed '"'s/.*load average: //'"')]"' >> "$tmux_wrapper_work"

	tmux_wrapper_build_bind

	tmux_wrapper_exec
}
tmux_wrapper_build_bind(){
	:
}
tmux_wrapper_bind(){
	if [ -z "$tmux_wrapper_initial_window_name" ]; then
		tmux_wrapper_initial_window_name=$2
	fi
	if [ -z "$tmux_wrapper_initial_window_path" ]; then
		tmux_wrapper_initial_window_path=$3
	fi
	echo bind $1 neww -n $2 '"ssh '$tmux_wrapper_host' -t '"'cd $3; bash'"'"' >> "$tmux_wrapper_work"
}
tmux_wrapper_exec(){
	if tmux -S "$tmux_wrapper_socket" has -t "$tmux_wrapper_session" 2> /dev/null; then
		tmux -S "$tmux_wrapper_socket" source "$tmux_wrapper_work"
		tmux -S "$tmux_wrapper_socket" attach -t "$tmux_wrapper_session"
		return
	fi

	if [ -z "$tmux_wrapper_initial_window_name" ]; then
		tmux_wrapper_exec_bare
		return
	fi
	if [ -z "$tmux_wrapper_initial_window_path" ]; then
		tmux_wrapper_exec_bare
		return
	fi

	tmux -S "$tmux_wrapper_socket" -f "$tmux_wrapper_work" new -s "$tmux_wrapper_session" -n "$tmux_wrapper_initial_window_name" "ssh $tmux_wrapper_host -t 'cd $tmux_wrapper_initial_window_path; bash'"
}
tmux_wrapper_exec_bare(){
	tmux -S "$tmux_wrapper_socket" -f "$tmux_wrapper_work" new -s "$tmux_wrapper_session" -n "$tmux_wrapper_session" "ssh $tmux_wrapper_host"
}
